### PR TITLE
Patching detect-secrets-stream image

### PR DESCRIPTION
**Pull request by krkazmier**
This PR updates Python dependencies for detect secrets stream; the efforts here are to resolve the vulnerabilities identified in previous Travis builds. 
- I added `RUN pip install pip==23.3` to the dockerfile itself to resolve the flagged vuln in this build: https://app.travis-ci.com/github/IBM/detect-secrets-stream/builds/269845161#L1819
- bumped python version to 3.9.18 to resolve this error: https://app.travis-ci.com/github/IBM/detect-secrets-stream/builds/269806317#L801
- `--skip-dirs "/pyroot/lib/python3.9/site-packages` has been added in order to ignore the false positive vuln, which Ross had opened up an issue for previously: https://github.com/aquasecurity/trivy/discussions/5772

PLEASE test this locally :) I am still working on spinning up a dev test instance to test locally ([instructions here](https://github.com/IBM/detect-secrets-stream/tree/main/kustomize_envs/dev#deploy-a-test-instance)) but I'm having issues with docker/buildx 

Once this is merged I will add the updates to the ibmcloud-secrets-manager branch

### CODE REVIEW

**Comment by sclinnell** [comment]
I think we need to merge this into ibm-cloud-secrets-manager branch no? (or is the plan to merge to main then pull changes into that branch?)

**Review by sclinnell — APPROVED** [review]
Clearly I didn't read the PR description.  YOU DA 💣

**Comment by krkazmier** [comment]
@williamsbritt do you have some time this week to test/review the changes here? Thank you :D

**Review by williamsbritt — COMMENTED** [review]
looks good to me!

**Pull request merged**
